### ISSUE TITLE
Remove Flyway trial

### ISSUE THREAD

**Issue by axelfontaine** [dvdtknsn/flOra#1]
Our license does not grant you redistribution rights. Please remove it from your repo.

**Comment by axelfontaine** [comment]
@dvdtknsn Friendly reminder: your repository is breaching by Boxfuse's Flyway Trial license as well as Oracle's JDBC driver license as neither allow free redistribution. Please correct ASAP.

**Comment by dvdtknsn** [comment]
I'll delete the repo. It's grossly out of date anyway.
